name: Publish to PyPI

on:
  push:
    branches: [master]

jobs:
  publish-to-test-pypi:
    if: startsWith(github.ref, 'refs/tags/v')  # only publish to PyPI on tag pushes that starts with v
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@master
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/


  publish-to-pypi:
    runs-on: ubuntu-latest
    environment: release
    needs:
      - publish-to-test-pypi
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@master
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
